### ISSUE TITLE
unexpected EOF while parsing (<string>, line 0)

### ISSUE THREAD

**Issue by albrox** [senshi-x/ComdirectPostboxDownloader#15]
After setting up everything and pressing 6 for downloading documents, I get the following:

```
You are using PushTAN. Please use your smartphone's Comdirect photoTAN app to validate the access request to your 'personal area'.
Please only continue once you have done so! Failure to validate this request for 5 consecutive times will result in your access being blocked.
Press ENTER after you have cleared the PushTAN challenge on your phone.
unexpected EOF while parsing (<string>, line 0)
Traceback (most recent call last):
  File "main.py", line 385, in <module>
    main = Main(dirname)
  File "main.py", line 29, in __init__
    self.showMenu()
  File "main.py", line 117, in showMenu
    self.__loadDocuments()
  File "main.py", line 154, in __loadDocuments
    messagesMeta = self.conn.getMessagesList(0, 1)
  File "/Users/USER/github_albrox/ComdirectPostboxDownloader/ComdirectConnection.py", line 276, in getMessagesList
    + json.dumps(r.json())
  File "/Users/USER/Library/Python/2.7/lib/python/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Any ideas?

**Comment by senshi-x** [comment]
Du verwendest Python 2.7, laut Readme/Doku wird Python 3.x benötigt.
