### ISSUE TITLE
Error: No module named requests

### ISSUE THREAD

**Issue by Metzger689** [senshi-x/ComdirectPostboxDownloader#26]
Hallo zusammen

Zunächst mal vielen Dank für die Möglichkeit die Gesamte Postbox von der comdirect ohne tausende Klicks herunterzuladen. Zugegeben ich bin ein blutiger Anfänger was Python etc. angeht, daher bitte ich schon jetzt um Nachsicht falls meine Frage absoluten noob Charakter hat :)

Entsprechend der Anleitung habe ich die settings.ini entsprechend angepasst und pip laufen lassen. wenn ich nun aber die main.py starte kommt folgende Rückmeldung:

MMacPro:ComdirectPostboxDownloader-2 metzger$ python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from ComdirectConnection import Connection
  File "/Users/metzger/Downloads/ComdirectPostboxDownloader-2/ComdirectConnection.py", line 1, in <module>
    import requests
ImportError: No module named requests

Offensichtlich hat er ein problem mit requests, was jedoch keine eigenständige Datei im Download folder ist. Im Requiremtents.txt habe ich einen requests eintrag gefunden aber wirklich anfangen kann ich damit leider nichts. Hoffe ihr könnt mir hier weiterhelfen.

Schonmald vielen Dank und Grüsse
Der Metzger ;)

**Comment by Metzger689** [comment]
Okay habs gefunden: 
Anscheinend musste ich explizit auf Python3 verweisen - hoffe das hilft dem einen oder anderen Noob :)

python3 -m pip install -r requirements.txt
python3 main.py 

LG
Metzger
